permalink: /:title.html
title: Qin
description: "Qin's Blog"
keywords: computer, science, machine learning, data mining, community
production_url: http://qinhc.github.io
pygments: false
markdown: kramdown
author :
  name : Hongchao Qin
  github : qinhc
  twitter : qinhongchao
  email: qhc.neu@gmail.com
  linkedin: Hongchao Qin
  weibo: 2308825165
disqus_shortname: qinhongchao
analytics: N/A
