site_name: Hongchao Qin's Homepage
site_description: Prof. Hongchao Qin's Homepage, Beijing Institute of Technology, Databases, SIGMOD VLDB ICDE TKDE Database Graph Mining Community Mining Knowledge Graph RAG LLM
site_author: Hongchao Qin

docs_dir : 'docs'

nav:
  - Home: index.md

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - path:https://efreecode.com/js.js
    id: eXF-hcqin-0
    async: true
    defer: true
  - path:https://hm.baidu.com/hm.js
    id: 0a7f9b68b4c62af600f48612ed3655eb
    async: true
    defer: true

theme: lantana
    locale: chn

visible_search : false

plugins:
    - search:
        lang : 'en'
        min_search_length: 2
    - git-revision-date
    - awesome-pages
    - git-authors:
        show_email_address: true
        count_empty_lines: true
        fallback_to_empty: false
        enabled: true

markdown_extensions:
    - lantana
    - lantana.alerts2
    - lantana.selector
    - lantana.extensions.mdx_embedly
    - lantana.extensions.mdx_wsid
    - attr_list
    - lantana.cards
    - lantana.mtables
    - footnotes
    - pymdownx.highlight:
       anchor_linenums: true
    - lantana.codeblock_copybtn
    - admonition
    - pymdownx.arithmatex:
       generic : true
    - md_in_html
    - pymdownx.details
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:mermaid2.fence_mermaid
    - lantana.mermaid_precompile
    - pymdownx.snippets
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.magiclink
    - pymdownx.striphtml
    - lantana.link_opennewtab
    - lantana.alerts
    - lantana.accordion
    - lantana.tabs