site_name: Hongchao Qin's Homepage
site_url: https://qinhc.github.io/
site_description: Prof. Hongchao Qin's Homepage, Beijing Institute of Technology, Databases, SIGMOD VLDB ICDE TKDE Database Graph Mining Community Mining Knowledge Graph RAG LLM
site_author: Hongchao Qin


theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: flase
  locale: en
  font:
    text: "Arial"
    code: "Consolas"
  highlightjs: true
  hljs_languages:
    - yaml
    - django

nav:
  - index.md

extra_javascript:
  - path:https://efreecode.com/js.js
    id: eXF-hcqin-0
    async: true
    defer: true
  - path:https://hm.baidu.com/hm.js
    id: 0a7f9b68b4c62af600f48612ed3655eb
    async: true
    defer: true

extra_css:
  - css/extra.css

exclude_docs: |
  *.py

markdown_extensions:
  - toc:
      permalink: 
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.snippets
  - pymdownx.superfences
  - callouts
  - mdx_gh_links:
      user: mkdocs
      repo: mkdocs
  - mkdocs-click


hooks:
  - docs/hooks.py

plugins:
  - autorefs

watch:
  - mkdocs